[["quan.tr.wh",1], "Message", {html: "<p>Anne: What color are the shapes?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_tr_1.html" }}],
[["quan.fa.wh",1], "Message", {html: "<p>Anne: What color are the shapes?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_fa_1.html" }}],
[["quan.ta.wh",1], "Message", {html: "<p>Anne: What color are the shapes?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_ta_1.html" }}],
[["quan.tr.wh",2], "Message", {html: "<p>Anne: Which shape is green?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_tr_2.html" }}],
[["quan.fa.wh",2], "Message", {html: "<p>Anne: Which shape is green?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_fa_2.html" }}],
[["quan.ta.wh",2], "Message", {html: "<p>Anne: Which shape is green?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_ta_2.html" }}],
[["quan.tr.wh",3], "Message", {html: "<p>Anne: What color are the shapes?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_tr_3.html" }}],
[["quan.fa.wh",3], "Message", {html: "<p>Anne: What color are the shapes?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_fa_3.html" }}],
[["quan.ta.wh",3], "Message", {html: "<p>Anne: What color are the shapes?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_ta_3.html" }}],
[["quan.tr.wh",4], "Message", {html: "<p>Anne: What shape is green?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_tr_4.html" }}],
[["quan.fa.wh",4], "Message", {html: "<p>Anne: What shape is green?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_fa_4.html" }}],
[["quan.ta.wh",4], "Message", {html: "<p>Anne: What shape is green?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_ta_4.html" }}],
[["quan.tr.wh",5], "Message", {html: "<p>Anne: What color are the shapes?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_tr_5.html" }}],
[["quan.fa.wh",5], "Message", {html: "<p>Anne: What color are the shapes?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_fa_5.html" }}],
[["quan.ta.wh",5], "Message", {html: "<p>Anne: What color are the shapes?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_ta_5.html" }}],
[["quan.tr.wh",6], "Message", {html: "<p>Anne: What shape is yellow?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_tr_6.html" }}],
[["quan.fa.wh",6], "Message", {html: "<p>Anne: What shape is yellow?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_fa_6.html" }}],
[["quan.ta.wh",6], "Message", {html: "<p>Anne: What shape is yellow?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_ta_6.html" }}],
[["quan.tr.wh",7], "Message", {html: "<p>Anne: What color are the shapes?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_tr_7.html" }}],
[["quan.fa.wh",7], "Message", {html: "<p>Anne: What color are the shapes?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_fa_7.html" }}],
[["quan.ta.wh",7], "Message", {html: "<p>Anne: What color are the shapes?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_ta_7.html" }}],
[["quan.tr.wh",8], "Message", {html: "<p>Anne: What shape is red?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_tr_8.html" }}],
[["quan.fa.wh",8], "Message", {html: "<p>Anne: What shape is red?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_fa_8.html" }}],
[["quan.ta.wh",8], "Message", {html: "<p>Anne: What shape is red?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_ta_8.html" }}],
[["quan.tr.wh",9], "Message", {html: "<p>Anne: What color are the triangles?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_tr_9.html" }}],
[["quan.fa.wh",9], "Message", {html: "<p>Anne: What color are the triangles?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_fa_9.html" }}],
[["quan.ta.wh",9], "Message", {html: "<p>Anne: What color are the triangles?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_ta_9.html" }}],
[["quan.tr.wh",10], "Message", {html: "<p>Anne: Which shape is blue?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_tr_10.html" }}],
[["quan.fa.wh",10], "Message", {html: "<p>Anne: Which shape is blue?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_fa_10.html" }}],
[["quan.ta.wh",10], "Message", {html: "<p>Anne: Which shape is blue?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_ta_10.html" }}],
[["quan.tr.wh",11], "Message", {html: "<p>Anne: What color are the triangles?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_tr_11.html" }}],
[["quan.fa.wh",11], "Message", {html: "<p>Anne: What color are the triangles?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_fa_11.html" }}],
[["quan.ta.wh",11], "Message", {html: "<p>Anne: What color are the triangles?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_ta_11.html" }}],
[["quan.tr.wh",12], "Message", {html: "<p>Anne: Which shape is red?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_tr_12.html" }}],
[["quan.fa.wh",12], "Message", {html: "<p>Anne: Which shape is red?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_fa_12.html" }}],
[["quan.ta.wh",12], "Message", {html: "<p>Anne: Which shape is red?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_ta_12.html" }}],
[["quan.tr.wh",13], "Message", {html: "<p>Anne: What color are the triangles?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_tr_13.html" }}],
[["quan.fa.wh",13], "Message", {html: "<p>Anne: What color are the triangles?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_fa_13.html" }}],
[["quan.ta.wh",13], "Message", {html: "<p>Anne: What color are the triangles?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_ta_13.html" }}],
[["quan.tr.wh",14], "Message", {html: "<p>Anne: Which shape is blue?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_tr_14.html" }}],
[["quan.fa.wh",14], "Message", {html: "<p>Anne: Which shape is blue?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_fa_14.html" }}],
[["quan.ta.wh",14], "Message", {html: "<p>Anne: Which shape is blue?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_ta_14.html" }}],
[["quan.tr.wh",15], "Message", {html: "<p>Anne: What color are the circles?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_tr_15.html" }}],
[["quan.fa.wh",15], "Message", {html: "<p>Anne: What color are the circles?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_fa_15.html" }}],
[["quan.ta.wh",15], "Message", {html: "<p>Anne: What color are the circles?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_ta_15.html" }}],
[["quan.tr.wh",16], "Message", {html: "<p>Anne: Which shape is yellow?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_tr_16.html" }}],
[["quan.fa.wh",16], "Message", {html: "<p>Anne: Which shape is yellow?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_fa_16.html" }}],
[["quan.ta.wh",16], "Message", {html: "<p>Anne: Which shape is yellow?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_ta_16.html" }}],
[["quan.tr.wh",17], "Message", {html: "<p>Anne: What color are the circles?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_tr_17.html" }}],
[["quan.fa.wh",17], "Message", {html: "<p>Anne: What color are the circles?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_fa_17.html" }}],
[["quan.ta.wh",17], "Message", {html: "<p>Anne: What color are the circles?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_ta_17.html" }}],
[["quan.tr.wh",18], "Message", {html: "<p>Anne: Which shape is black?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_tr_18.html" }}],
[["quan.fa.wh",18], "Message", {html: "<p>Anne: Which shape is black?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_fa_18.html" }}],
[["quan.ta.wh",18], "Message", {html: "<p>Anne: Which shape is black?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_ta_18.html" }}],
[["quan.tr.wh",19], "Message", {html: "<p>Anne: What color are the squares?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_tr_19.html" }}],
[["quan.fa.wh",19], "Message", {html: "<p>Anne: What color are the squares?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_fa_19.html" }}],
[["quan.ta.wh",19], "Message", {html: "<p>Anne: What color are the squares?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_ta_19.html" }}],
[["quan.tr.wh",20], "Message", {html: "<p>Anne: What shape is orange?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_tr_20.html" }}],
[["quan.fa.wh",20], "Message", {html: "<p>Anne: What shape is orange?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_fa_20.html" }}],
[["quan.ta.wh",20], "Message", {html: "<p>Anne: What shape is orange?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_ta_20.html" }}],
[["quan.tr.wh",21], "Message", {html: "<p>Anne: What color are the squares?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_tr_21.html" }}],
[["quan.fa.wh",21], "Message", {html: "<p>Anne: What color are the squares?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_fa_21.html" }}],
[["quan.ta.wh",21], "Message", {html: "<p>Anne: What color are the squares?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_ta_21.html" }}],
[["quan.tr.wh",22], "Message", {html: "<p>Anne: What shape is orange?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_tr_22.html" }}],
[["quan.fa.wh",22], "Message", {html: "<p>Anne: What shape is orange?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_fa_22.html" }}],
[["quan.ta.wh",22], "Message", {html: "<p>Anne: What shape is orange?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_ta_22.html" }}],
[["quan.tr.wh",23], "Message", {html: "<p>Anne: What color are the squares?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_tr_23.html" }}],
[["quan.fa.wh",23], "Message", {html: "<p>Anne: What color are the squares?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_fa_23.html" }}],
[["quan.ta.wh",23], "Message", {html: "<p>Anne: What color are the squares?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_ta_23.html" }}],
[["quan.tr.wh",24], "Message", {html: "<p>Anne: What shape is black?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_tr_24.html" }}],
[["quan.fa.wh",24], "Message", {html: "<p>Anne: What shape is black?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_fa_24.html" }}],
[["quan.ta.wh",24], "Message", {html: "<p>Anne: What shape is black?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "quant_ta_24.html" }}],
[["filler.good.",1], "Message", {html: "<p>Anne: Are there more hearts than circles?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "filler_good_1.html" }}],
[["filler.good.",2], "Message", {html: "<p>Anne: Are there more stars than moons?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "filler_good_2.html" }}],
[["filler.bad.",3], "Message", {html: "<p>Anne: Are there more diamonds than hearts?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "filler_bad_3.html" }}],
[["filler.good.",4], "Message", {html: "<p>Anne: Are the shapes different from each other?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "filler_good_4.html" }}],
[["filler.bad.",5], "Message", {html: "<p>Anne: Are there different shapes?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "filler_bad_5.html" }}],
[["filler.bad.",6], "Message", {html: "<p>Anne: Are the shapes the same?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "filler_bad_6.html" }}],
[["filler.good.",7], "Message", {html: "<p>Anne: Where is the heart?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "filler_good_7.html" }}],
[["filler.good.",8], "Message", {html: "<p>Anne: Where is the diamond?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "filler_good_8.html" }}],
[["filler.bad.",9], "Message", {html: "<p>Anne: Is the triangle below the moon?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "filler_bad_9.html" }}],
[["filler.good.",10], "Message", {html: "<p>Anne: Is the star next to the diamond?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "filler_good_10.html" }}],
[["filler.bad.",11], "Message", {html: "<p>Anne: Where is the moon?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "filler_bad_11.html" }}],
[["filler.bad.",12], "Message", {html: "<p>Anne: Are there fewer hearts than stars?</p><p><i>Press any key to continue.</i></p>"},"VraagX", {html:{ include: "filler_bad_12.html" }}],
